#! /bin/sh
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config merge_overlapping_monitors true 
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true 

polybar-msg cmd restart

~/.fehbg
