#!/bin/zsh

function send_notification {
  brightness=$(printf "%.0f" $(xbacklight -get))

  if (( brightness < 34 )); then
    brightnessLevel="low"
  elif (( brightness < 67 )); then
    brightnessLevel="medium"
  else
    brightnessLevel="high"
  fi

  icon="/usr/share/icons/Papirus-Dark/symbolic/status/display-brightness-$brightnessLevel-symbolic.svg"

  dunstify -i $icon -r 2593 -u normal "Brightness is at $brightness"
}

case $1 in
  up)
    xbacklight -inc 10
    send_notification
    ;;
  down)
    xbacklight -dec 10
    send_notification
    ;;
esac
