#!/bin/bash

lang=$(xkblayout-state print %s | awk '{print toupper($0)}')

datetime=$(LC_TIME=en_US.UTF-8 date '+%a, %b %d %H:%M')

sound=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')

notify-send "date: $datetime
sound: $sound
lang: $lang"
