#!/bin/bash

# Script modified from these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

function get_volume {
  amixer get $1 | grep '%' | head -n 1 | awk '{print $5}' | grep -o '[0-9]\+'
}

function is_mute {
  amixer get $1 | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

iconPath="/usr/share/icons/Papirus-Dark/symbolic/status"

function send_notification {
  if [ $1 == 'Capture' ] ; then 
    iconSound="$iconPath/audio-input-microphone-high-symbolic.svg"
    iconMuted="$iconPath/audio-input-microphone-muted-symbolic.svg"
    device="Microphone"
    textActive="is active"
  else
    vol=$(get_volume $1)

    if (( vol < 34)); then
      volLevel='low'
    elif (( vol < 67 )); then
      volLevel='medium'
    else
      volLevel='high'
    fi

    iconSound="$iconPath/audio-volume-$volLevel-symbolic.svg"
    iconMuted="$iconPath/audio-volume-muted-symbolic.svg"
    device="Volume"
    textActive="is at $vol"
  fi

  if is_mute $1 ; then
    dunstify -i $iconMuted -r 2593 -u normal "$device is muted"
  else
    dunstify -i $iconSound -r 2593 -u normal "$device $textActive"
  fi
}

case $1 in
  volume_up)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 5%+ > /dev/null
    send_notification Master
    ;;
  volume_down)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 5%- > /dev/null
    send_notification Master
    ;;
  volume_mute)
    amixer -D pulse set Master 1+ toggle > /dev/null
    send_notification Master
    ;;
  capture_mute)
    amixer -D pulse set Capture toggle > /dev/null
    send_notification Capture
    ;;
esac
